IMAGE=carylorrk/woops
CONTAINER=woops

all: build

attach:
	nvidia-docker exec -it $(CONTAINER) bash

rmf:
	docker rm -f $(CONTAINER)

stop:
	docker stop $(CONTAINER)

start:
	nvidia-docker start $(CONTAINER)

run:
	mkdir -p cache volume
	nvidia-docker run -d -P --name $(CONTAINER) -v `pwd`/volume:/root/volume -v `pwd`:/root/woops -v `pwd`/cache:/root/.cache $(IMAGE)

build:
	docker build -t $(IMAGE) .

.PHONY: build run start stop rmf attach
